### PR TITLE
Improved the look of the hiring button

### PR DESCRIPTION
**Pull request by neauoire**
Improved the look of the Hiring button. Current online version is not vertically centred and looks a bit clunky.

## Before
screen shot 2018-02-05 at 4 19 37 pm

## After
screen shot 2018-02-05 at 4 19 32 pm

## On Hover
screen shot 2018-02-05 at 4 19 29 pm

### CODE REVIEW

**Comment by neauoire** [comment]
It is now vertically entered with the Chia Logo.

screen shot 2018-02-05 at 4 16 23 pm

**Comment by neauoire** [comment]
The second commit improves the readability of the mission from

## Before

screen shot 2018-02-05 at 4 44 55 pm

## After
screen shot 2018-02-05 at 4 45 00 pm

**Comment by ashadle** [comment]
@neauoire I ended up redesigning the website so I'm going to go ahead and close this PR.

**Comment by neauoire** [comment]
No problem, good call. I'm excited to see the new version.

**Pull request closed without merging**
