### PR TITLE
Fix spacing of news feed items for small screens

### PR DESCRIPTION
**Pull request by pwindle**
Saw this being reported in the keybase chat and see you've just added [issue #126 (News page not responsive)](https://github.com/Chia-Network/website/issues/126)

Just a couple of lines of css.

### CODE REVIEW

**Comment by pwindle** [comment]
Here's a screenshot
news

**Comment by pwindle** [comment]
Added some more changes. Let me know if I have to rename the pull request or something.

**Comment by ashadle** [comment]
@pwindle would you mind resolving the conflicts so I can merge your changes?  Thank you!

**Comment by pwindle** [comment]
Linking another related issue:
[Issue 109 - Mobile responsive on site](https://github.com/Chia-Network/website/issues/109)

**Comment by ashadle** [comment]
@pwindle would you mind fixing the conflicts so I can merge this?

**Comment by pwindle** [comment]
Hope you don't mind unclean commit history.

**Comment by pwindle** [comment]
conflict2

**Pull request closed without merging**
