### PR TITLE
Japanese page translation

### PR DESCRIPTION
**Pull request by katabame**
I translated the index page to Japanese.
But this is translate only, there isn't language switcher.

As #3 says, there is no guide lines to translate.
When guideline to translate is ready, please let me know.

### CODE REVIEW

**Comment by DatDraggy** [comment]
I would suggest we put each language in it's own directory inside a "language" directory. So, for example for japanese it would be in webroot/languages/ja/
That way people can easily add their language to it without clogging the webroot directory.

**Review by DatDraggy — CHANGES_REQUESTED** [review]
add another directory called "languages" in webroot where the "ja" directory goes for better overview of the webroot directory.
Eg "weboort/languages/ja/index.html"

**Comment by katabame** [comment]
Sure, I moved the file into `languages` folder

**Comment by DatDraggy** [comment]
Awesome

**Comment by richardkiss** [comment]
We've merged in Japanese translation in https://github.com/Chia-Network/website/pull/10 and it looks like it includes contributions from you, so thank you for that. I'll close this pull request, but feel free to submit others if you have any other translation to offer.

**Pull request closed without merging**
