### PR TITLE
Content security policy and subresource integrity

### PR DESCRIPTION
**Pull request by dkackman**
This includes [Content Security Policy](https://content-security-policy.com/) declarations and [Subresource Integrity hashes](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) for external resources.

Looking for review and feedback as there are development implications to both CSP and SRI.

**Rationale**
Though there is not much of an attack surface right now, given the nature of the Chia and its website, it is a good idea to implement these technologies now, while the website is simple, setting the pattern for the future.

*CSP*
A Content Security Policy declares where resources can be loaded from. This prevents browsers from loading scripts, styles etc from locations other than those explicitly white-listed, protecting against various forms of cross-site scripting attacks.

As written, this set of CSP directives:
- whitelists the handful of CDN's that supply flexbox, js-cookie, google-fonts, jquery etc
- includes the 'unsafe-inline' directive for styles. This allows continued use of inline styles, which do present an [attack surface](https://stackoverflow.com/questions/41925390/what-are-the-risks-associated-with-using-inline-styles). The flip side, if inline styles are disallowed it can make one off style tweaks a pain as all styles require external CSS entries. It's best practice to put all styles in external stylesheets.
- precludes the use of any embedded script blocks

*SRI*
- All of the externally hosted resources include an SRI hash. Browsers will compare the embedded hash to the resource's hash and prevent their loading if they do not match. This prevents attacks that might come from a compromised CDN
- The google fonts do not include an SRI hash. Google fonts return different resources based on browser so don't work very well with SRI.

### CODE REVIEW

**Comment by ashadle** [comment]
@dkackman can you resolve the conflicts?

**Comment by dkackman** [comment]
@ashadle will do - this PR is pretty old so there's some changes to the newer html that I'll need to make.

CSP, by default, prevents eval and unsigned inline scripts. Do you have any thoughts on mandating that all scripts reside in external script files? My preference would be to go with as strict a policy as possible.

**Comment by ashadle** [comment]
@dkackman that sounds great and I agree all inline css should only be on external style scripts.

**Comment by dkackman** [comment]
@ashadle cool - i'll get things updated in the next couple of days and add a note to the readme that scripts and css need to be external to the html.

On a side note I notice that the main index.html does not include `<script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js">` while the other two do. Oversight or by design?

**Comment by dkackman** [comment]
@ashadle Looks like there are some compromises that need to be made in order to use Google Tag Manager. 

From [this blog post](https://www.lunametrics.com/blog/2017/07/20/using-google-analytics-google-tag-manager-content-security-policy/):
> JavaScript
Like Google Analytics, Google Tag Manager requires enabling two sources of JavaScript. Unlike Google Analytics, there is no workaround for allowing ‘unsafe-inline’ script execution. Tag Manager is fundamentally a script-injection framework. Its entire purpose is to dynamically load and execute pieces of JavaScript onto your page. It is not feasible to restrict Tag Manager from executing inline snippets. In order for Tag Manager to function, then your script-src (or default-src) directive must be updated to include https://www.googletagmanager.com and ‘unsafe-inline’ (with the quotes) in the source list.

So we can block all inline scripts (more secure) or allow them and use google tag manager (less secure).

Please let me know which direction to implement.

**Comment by ashadle** [comment]
@dkackman good catch! I just updated the index.html file with the correct google analytics language.

**Comment by dkackman** [comment]
@ashadle Conflicts resolved

I can't test whether or not google tag manager and analytics still work. They do not throw any client side errors.

**Comment by ashadle** [comment]
Hi There, thank you so much for submitting this PR. We are rebranding the website and will have updated copy so I'm going to close out this ticket. Thank you!

**Pull request closed without merging**
